CUSTOM_AIRBORNE_HELMET(Biscuit);
CUSTOM_AIRBORNE_HELMET(Lucifer);
CUSTOM_AIRBORNE_HELMET(Crys);
CUSTOM_AIRBORNE_HELMET(Rook);
CUSTOM_AIRBORNE_HELMET(Nitro);
CUSTOM_AIRBORNE_HELMET(Floyd);
CUSTOM_AIRBORNE_HELMET(Havocc);
